# Using GitHub actions
# See details here:
# https://github.com/marketplace/actions/sphinx-to-github-pages
---
name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master]  # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      # See https://sphinx.silverrainz.me/pages/ for details
      uses: sphinx-notes/pages@v3
